### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by milanlanet** [gamenet/php-jabber-rpc#3]
i am using this

 $rpc = new \GameNet\Jabber\RpcClient([
        'server' => 'http://192.168.200.17:4560',
        'host' => 'lanetteam.com',
        'debug' => false,
    ]);

`$username='user4';
    $contacts = $rpc->getRoster($username);`

> I am getting this below error. What may be the issue?

`Fatal error: Uncaught exception 'RuntimeException' with message 'Error execution command 'get_roster'' with parameters array ( 'user' => 'user4', 'host' => 'lanetteam.com', ). Response: ' in /var/www/html/ejabber/vendor/gamenet/php-jabber-rpc/lib/GameNet/Jabber/RpcClient.php:96 Stack trace: #0 /var/www/html/ejabber/vendor/gamenet/php-jabber-rpc/lib/GameNet/Jabber/Mixins/RosterTrait.php(63): GameNet\Jabber\RpcClient->sendRequest('get_roster', Array) #1 /var/www/html/ejabber/index.php(14): GameNet\Jabber\RpcClient->getRoster('user4') #2 {main} thrown in /var/www/html/ejabber/vendor/gamenet/php-jabber-rpc/lib/GameNet/Jabber/RpcClient.php on line 96`

**Comment by misterion** [comment]
From stack trace i see your server return invalud xmlrpc response - an empty string. What is your jabber server?

**Comment by misterion** [comment]
Close as unanswered in more then month.
