### ISSUE TITLE
Unknow call

### ISSUE THREAD

**Issue by ananda-agrawal** [gamenet/php-jabber-rpc#4]
I always get this error while calling register, as 

Error -112 Unknown call: {call,check_account, [{

which works fine from command line ejabberdctl.

**Comment by misterion** [comment]
Please look at for dirty solution https://github.com/gamenet/php-jabber-rpc/issues/2

**Comment by ananda-agrawal** [comment]
It works by sending an array of username, password and server, was sending host instead.
